module.exports = {
  serect: "ChatRoomOfPC",
  list: [
    "gaoshuo",
    "liuxiaojun",
    "houxin",
    "zhanghao",
    "wangjiayi",
    "wanjinhao",
    "liujunhao",
    "luhaitian",
    "sunsiyuan",
    "dupeiyu",
    "guoyuzhong",
  ],
  isUsed: {
    gaoshuo: false,
    liuxiaojun: false,
    houxin: false,
    zhanghao: false,
    wangjiayi: false,
    wanjinhao: false,
    liujunhao: false,
    luhaitian: false,
    sunsiyuan: false,
    dupeiyu: false,
    guoyuzhong: false,
  },
}